### PR TITLE
Tic-tac-toe  milestone-1

### PR DESCRIPTION
**Pull request by ahmetbozaci**
Deat TSE,

1. We created two folder: **lib and bin**
2. We created **main.rb** in bin folder.
3. Change executable to **main.rb** file

### CODE REVIEW

**Review by layzrd — CHANGES_REQUESTED** [review]
### Status: Invalid  ↩️
Hi @ahmetbozaci, 👏 You did very well on this project. I appreciate your efforts to achieve this milestone 🦍. Kindly fix the following issues.
[REQUIRED]
In this project, you should use GitFlow instead of GitHub flow. [https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/gitflow.png](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/gitflow.png)
To go deeper, read the following article [https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow)

Once you fix the issues, kindly submit another code review. ♲

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/)

**Comment by ahmetbozaci** [comment]
Dear TSE,

- I added **develop branch** and set it **default branch.**
- **Working branch** will be **feature-branch.**

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required 
**Hi there**
nice job implementing all of the required changes, but there are still some changes to be made:

- [x] Please make your main file executable.

please make this change and submit for another code review

**Comment by ahmetbozaci** [comment]
Dear TSE,

- We already make executable main.rb file but ı think something broken after create develop branch.
- We fixed it.
- When we write **"bin/main.rb"** on terminal we can see output from file.

**Review by PhillipUg — APPROVED** [review]
# Status: Project Approved! 🥇 

Congratulations on making all the requested changes and getting this project approved. :+1:

You can merge this branch into the development branch when you're ready and go on to your next milestone.
:bulb:  Do not forget to submit your project completion form after merging this branch.

All the best team,

For any assistance, you can contact me on slack as **Phillip Musiime**

**Pull request merged**
